---
# tasks file for ./deploy_local_scripts
- name: Create user scripts folder
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ user_scripts_folder }}"
    - "{{ user_scripts_folder }}/lib"

- name: Template scripts
  template:
    src: "{{ item }}"
    dest: "{{ user_scripts_folder }}"
    mode: "u+x"
  with_fileglob:
    - ../templates/*

- name: Template lib
  template:
    src: "{{ item }}"
    dest: "{{ user_scripts_folder }}/lib"
    mode: "u+x"
  with_fileglob:
    - ../templates/lib/*
