#!/bin/bash

DESIRED_WINDOW=$(xdotool search --limit 1 --desktop 0 "$1")
NOT_FOUND=$?
if [[ "${NOT_FOUND}" == 1 ]]
  then
  # application not running, run app
  "$2"
else
  ACTIVE_WINDOW=$(xdotool getactivewindow)
  if [[ "${DESIRED_WINDOW}" == ${ACTIVE_WINDOW} ]]
    then
      xdotool windowminimize "${ACTIVE_WINDOW}"
  else
    xdotool windowactivate "${DESIRED_WINDOW}"
  fi
fi
