#!/bin/bash

# TOOLS_PERFORM_AUTO_DEPLOY
if [ -z "$TOOLS_PERFORM_AUTO_DEPLOY" ]; then
  echo "No autodeploy";
else
    if [ "$TOOLS_PERFORM_AUTO_DEPLOY" = true ]; then
      echo "Starting autodeploy"
      ansible-playbook -i ./inventory/localhost playbook-local.yml
    else
      echo "Variavle set to false"
    fi
fi
