---
- name: Deploy local .bashrc file
  template:
    src: bashrc.j2
    dest: "{{ user_home_dir }}/{{ local_bashrc_file }}"
    mode: 0644

- name: Deploy local .screenrc file
  template:
    src: screenrc.j2
    dest: "{{ user_home_dir }}/{{ local_screenrc_file }}"
    mode: 0644

- name: Deploy local git condig file
  template:
    src: gitconfig.j2
    dest: "{{ user_home_dir }}/{{ local_gitconfig_file }}"
    mode: 0644
